texts/models.py
from django.db import models
from django.utils.text import slugify

from gentext.models.structure import SlugModel
from gentext.managers.queryset import PageQuerySet


class Text(SlugModel):
    '''
    Model for novel,
        has some simple information about a book.
        It does NOT allow searching by publisher (no ManyToManyField).
    '''
    title = models.CharField(max_length=50)
    author = models.CharField(max_length=255, blank=True, default='James Joyce')
    publisher = models.CharField(max_length=255, blank=True)
    publication_date = models.PositiveSmallIntegerField(blank=True)
    info = models.TextField(max_length=1000, blank=True, null=True)

    def __unicode__(self):
        return self.title

    def short(self):
        '''
        Create title abbreviation
        '''
        if self.title == 'Finnegans Wake':
            return 'FW'
        elif self.title == 'Ulysses':
            return 'U'


class Section(models.Model):
    '''
    Model for sections ("books") that are sometimes part of a novel.
    '''
    text = models.ForeignKey(Text, related_name='section_set')
    title = models.CharField(max_length=255, blank=True)

    def __unicode__(self):
        return self.title


class Chapter(models.Model):
    '''
    Model for novel chapters
    '''
    text = models.ForeignKey(Text)
    section = models.ForeignKey(Section, blank=True, null=True)

    number = models.PositiveSmallIntegerField()
    title = models.CharField(max_length=255, blank=True)

    slug = models.SlugField(max_length=50, blank=True)

    def __unicode__(self):
        if self.section:
            return u'{0}.{1}'.format(self.section, self.number)
        else:
            return u'{}'.format(self.number)

    def save(self, *args, **kwargs):
        # override save() to make a unique slug on save
        if not self.slug:
            if self.section:
                self.slug = slugify('{0}{1}'.format(self.booksection, self.number))
            else:
                self.slug = '{}'.format(self.number)
        super(Chapter, self).save(*args, **kwargs)


class Page(models.Model):
    '''
    Model for a text page
    '''
    text = models.ForeignKey(Text)
    section = models.ForeignKey(Section, blank=True, null=True)
    chapter = models.ForeignKey(Chapter, blank=True, null=True)

    page_number = models.PositiveSmallIntegerField()

    slug = models.SlugField(unique=True, max_length=50, blank=True)

    # manager
    objects = PageQuerySet.as_manager()

    def __unicode__(self):
        return '{0} {1}'.format(self.text.short(), self.page_number)

    def save(self, *args, **kwargs):
        # override save() to make a unique slug on save
        if not self.slug:
            self.slug = '{0}-{1}'.format(self.text.short().lower(), self.page_number)
        super(Page, self).save(*args, **kwargs)


class Line(models.Model):
    '''
    Model for each line of a text
    '''
    text = models.ForeignKey(Text, blank=True, null=True)
    section = models.ForeignKey(Section, blank=True, null=True)
    chapter = models.ForeignKey(Chapter, blank=True, null=True)
    page = models.ForeignKey(Page, blank=True, null=True)

    linenumber = models.CharField(max_length=10, null=True)
    content = models.TextField(null=True)

    def __unicode__(self):
        return u'{0}\t{1}'.format(self.linenumber, self.content)

    def short(self):
        return u'{0} {1}'.format(self.text.short(), self.linenumber)

texts/views.py
from django.views.generic import TemplateView

from haystack.views import SearchView

from texts.models import Text, Line
from gentext.views.item import ItemView
from gentext.views.page import PageView


TEXTS_DUMMY_BASE = 'texts/dummy_base.html'


class TextsHomeView(TemplateView):
    template_name = 'texts/base.html'

    def get_context_data(self, **kwargs):
        context = super(TextsHomeView, self).get_context_data(**kwargs)
        context['linecount'] = Line.objects.count()
        context['textcount'] = Text.objects.count()
        context['texts'] = Text.objects.all()
        return context


class TextsSearchView(SearchView):
    template = 'texts/search_results.html'

    def extra_context(self, **kwargs):
        return {'specific_model': 'models=texts.line'}


class TextView(ItemView):
    model = Text
    slug_name = 'slug'
    template = 'texts/item.html'
    dummybase_template = TEXTS_DUMMY_BASE

    def sections(self):
        return self.item.section_set.all()

    def notebooks(self):
        return self.item.notebook_set.count()


class TextPageView(PageView):
    itemslug = 'slug'
    pageslug = 'page'

    parent_model = Text
    template = 'texts/page.html'
    dummybase_template = TEXTS_DUMMY_BASE

    def get_page(self):
        # override
        return self.pageQ.get(page_number=self.kwargs[self.pageslug])

    def get_context_data(self, **kwargs):
        # override
        context = super(TextPageView, self).get_context_data(**kwargs)
        context['lines'] = self.object.line_set.all()
        return context

texts/templates/texts/base.html
{% extends 'JJDLP/dummy_base.html' %}
{% load staticfiles %}
{% load markdown_filter %}


{% block heads %}
<link rel="stylesheet" href="{% static 'JJDLP/css/homepage.css' %}"/>
{% endblock %}


{% block title %}Texts{% endblock %}


{% block body %}
<div class="homepage-wrap">
	
	<div class="module module-header">
		<div class="left">
			<div class="title">James Joyce's texts</div>
			<div class="info"></div>
			<div class="module-counter">
				Texts: <strong>{{ textcount }}</strong>
				<br/>
				Lines: <strong>{{ linecount }}</strong>
			</div>
		</div>

		<div class="search">
			<form class="form-wrap" action="{% url 'notebooks_fast_search' %}" method="get">
				<input class="form-control" id="searchquery" type="text" name='q' placeholder="Search text lines...">
				<input type="hidden" name="models" value="texts.line" />
				<button class="searchbutton btn btn-default" type="submit">Search</button>
			</form>
			<div style="text-align: right;float: right;">
				<a href="{% url 'haystack_search' %}">advanced search</a>
			</div>
		</div>
	</div>

<hr/>
	<table id="head_banner">
	<tr>
	</tr>
	</table>
	<div class="chart-info" style="color:#999; margin-top: 15px; margin-left: 15px;">
		<span class="small"></span>
	</div>
<hr style="margin-top: 5px;" />

	<div class="texts">
		<div class="viewer">
			<div class="module-title">
				<div class="module-info">
					<p>Text blabla</p>
				</div>		
				<span class="title-text">Available texts</span>
				<div class="module-info">
					<p>more text blabla</p>
				</div>
			</div>
			<div class="col-md-12">
				{% for text in texts %}
				<div class="pane">
					<div class="pane-title">
						{{text}}
					</div>
					<div class="pane-body">{{ text.info|markdownify|safe }}</div>
					<a class="pane-link notunderline" href="{% url 'texts_item' text.slug %}"><span class="pane-link-text">more</span> <span class="glyphicon glyphicon-link"></span></a>
				</div>
				{% endfor %}
			</div>
		</div>
	</div>

</div>

{% endblock %}

texts/templates/texts/dummy_base.html
{% extends 'JJDLP/dummy_base.html' %}

{% block title %}Texts{% endblock %}

{% block extra_tools %}
<div class="s">
	<form action="{% url 'texts_fast_search' %}" method="get">
			<input class="form-control" id="searchquery" type="text" name='q' placeholder="Search text lines...">
			<input type="hidden" name="models" value="texts.line" /> 
	</form>
</div>
{% endblock %}

{% block body %}
	<section id="content">
		{% block content %}
			Oops, you have found a hidden page! This is rather problematic, so please contact the developers.
		{% endblock %}
	</section>
{% endblock %}

texts/templates/texts/includes/texts_searchresults.html
{% load highlight %}

<div class="result-element">
    <div class="result-item">
        <a class="notred notunderline" href="{% url 'texts_page' result.object.text.slug result.object.page.page_number %}">
            {{result.object.short}}
            &emsp;
            {% with result.object.content|safe as content %}
            {% highlight content with query max_length 100000000 %}
            {% endwith %}
        </a>
    </div>
</div>
<hr class="search-hr" />

texts/templates/texts/item.html
{% extends 'gentext/catalogue.html' %}
{% load staticfiles %}
{% load markdown_filter %}
{% load humanize %}

{% block heads %}
{% endblock %}


{% block item_title %}
	<div class="small" style="margin-bottom: 1em;"><span class="glyphicon glyphicon-book"></span> {% if item.item_type %}{{ item.item_type|title }}{% else %}Text{% endif %}</div>
	{{ item }}
{% endblock %}


{% block description %}
	<div class="titleinfo">
		{% if item.publication_date %}{{ item.publication_date }}{% endif %}
		<br/>
		{% if item.publisher %}{{ item.publisher }}{% endif %}
	</div>
{% endblock %}


{% block info %}{{ item.info|markdownify|safe }}{% endblock %}


{% block nav %}
	<div class="list-group">
		<a class="list-group-item notred" href="{% url 'notebooks_home' %}">
			<span class="glyphicon glyphicon-list-alt"></span> {{ view.notebooks }} notebook{{ view.notebooks|pluralize }}
		</a>
	</div>
{% endblock %}


{% block grid %}
	{% for section in view.sections %}
		{% for chapter in section.chapter_set.all %}
		<div>
			{{ chapter }}: pp. {{ chapter.page_set.first.page_number }} - {{ chapter.page_set.last.page_number }}
		</div>
		{% endfor %}
	{% endfor %}

	<div class="pagination">
		Go to page 
	    <select class="selector" onchange="location = this.options[this.selectedIndex].value;">
	    	{% for page in collection_list %}
	    	<option value="{% url 'texts_page' slug=item.slug page=page.page_number %}">{{ page.page_number }}</option>
	    	{% endfor %}
	    </select>
    </div>
{% endblock %}

texts/templates/texts/page.html
{% extends 'gentext/desk.html' %}
{% load stringoperations %}

{% block heads %}
{% endblock %}

{% block item_title %}
<div class="small" style="margin-bottom: 1em;"><span class="glyphicon glyphicon-list-alt"></span> Page</div>
{{ current_page }}
{% endblock %}

{% block description %}
<div class="titleinfo">
	{{ item }}
</div>
{% endblock %}



{% block content_division %}
{% endblock %}


{% block grid %}

<div id="detail">
	<div class="novel_page">
	{% if lines %}
		<div class="panel panel-default">
			<div class="panel-body">
				<div class="djpagination" style="margin-top: 10px;" id="pag_info">
					{% if previous_page %}
					<a href="{% url 'texts_page' item.slug previous_page.page_number %}">&#171;</a> {{ previous_page.page_number }} |
					{% endif %}
					<strong>{{ current_page.page_number }}</strong>
					{% if next_page %}
					| {{ next_page.page_number }} <a href="{% url 'texts_page' item.slug next_page.page_number %}">&#187;</a>
					{% endif %}
				</div>
			
				<table style="margin-bottom: 20px;">
					{% for line in lines %}
					<tr class="linenumber" id="{{ line.linenumber }}">
						<td>{{ line.content|safe }}</td>
						<td style="float: right;">{% if line.linenumber|splitondot != '99' %}{{ line.linenumber|splitondot }}{% endif %}</td>
					</tr>
					{% endfor %}
				</table>
		</div>
	{% endif %}
	</div>    
</div>

{% endblock %}

texts/templates/texts/search_results.html
{% extends 'texts/dummy_base.html' %}
{% load staticfiles %}

{% block extra_tools %}
{% endblock %}

{% block content %}
<div class="books_list">
	{% if query %}
	<div class="left-paginator">
		<div class="more-search">
			<form class="form-wrap" action="{% url 'texts_fast_search' %}" method="get">
				<input class="form-control" id="searchquery" type="text" name='q' placeholder="Search text lines...">
				<input type="hidden" name="models" value="texts.line" />
				<button class="searchbutton btn btn-default" type="submit">Search</button>
			</form>
			<div style="text-align: right;float: right;">
				<a href="{% url 'haystack_search' %}">advanced search</a>
			</div>
		</div>
	</div>
	<div class="search-results">
		{% with page as page_obj %}
		{% include 'gentext/includes/count_paginator.html' %}
		{% endwith %}
		<hr class="pag-hr"/>
		{% with result_list=page.object_list %}
		{% if result_list %}
			{% for result in result_list %}
				{% include 'texts/includes/texts_searchresults.html' %}
			{% empty %}
			<div class="fail">
				No sources matched your search criteria "<strong>{{ query }}</strong>". Modify your existing search or try a new query.
			</div>
			{% endfor %}
		{% endif %}
		{% endwith %}

		{% with page as page_obj %}
		{% include 'gentext/includes/nums_paginator.html' %}
		{% endwith %}
	</div>
	{% else %}
	<div class="pagination" id="pag_info">No search query found</div>
	{% endif %}
</div>
{% endblock %}